config/_default/config.toml

resolve https://github.com/karmada-io/website/issues/17
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

update copyright year

---

data/en/banner.yml
layouts/partials/banner.html

Signed-off-by: afzal442 <afzal442@gmail.com>
I have changed Github text to `Learn More` since this is already used as icon above.

Overrides the github link and adds docs button

---

themes/meghna-hugo/assets/css/style.css

resolve https://github.com/karmada-io/website/issues/20
/assign @RainbowMango

fix cloud native img

---

layouts/partials/banner.html
themes/meghna-hugo/assets/css/style.css

resolve https://github.com/karmada-io/website/issues/15

fix hero area on tablet

---

layouts/partials/footer.html

resolve https://github.com/karmada-io/website/issues/25

Accessibility add link name

---

layouts/partials/about.html

resolve https://github.com/karmada-io/website/issues/28

fix items on tablet & mobile

---

src/pages/styles.module.css

resolve https://github.com/karmada-io/website/issues/43

fix hero logotype

---

OWNERS

/kind cleanup
Setup code owners. 
Fixes #

Setup code owners

---

src/css/custom.css
src/pages/index.js

resolve https://github.com/karmada-io/website/issues/44

content centering

---

.github/ISSUE_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE.md

/kind cleanup
Set up issue and PR template.
Fixes #

Setup issue and PR template

---

src/pages/index.js

It rescales `how it works` image.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
Signed-off-by: Rupesh Gelal <rupeshgelal9@gmail.com>

How it works rescaled

---

src/components/supportersList.js
src/data/supporters.js
src/pages/index.js

resolve https://github.com/karmada-io/website/issues/52

refactoring supporters block

---

src/pages/styles.module.css

resolve https://github.com/karmada-io/website/issues/54

fix logo on mobile

---

src/css/custom.css
src/pages/index.js

fix ui
/kind feature
resolve https://github.com/karmada-io/website/issues/62

Add more spaces above Why Karmada

---

src/css/custom.css

fix block
Add one of the following kinds:
/kind bug
/kind design
resolve https://github.com/karmada-io/website/issues/71

update supporters block on dark theme

---

src/components/featuresList.js
src/data/features.js
src/pages/index.js

Add one of the following kinds:
/kind cleanup
/kind feature
refactor
resolve https://github.com/karmada-io/website/issues/69

refactor Why Karmada list

---

static/favicons/site.webmanifest

minor update
add data for browser
resolve https://github.com/karmada-io/website/issues/92

minor update site.webmanifest

---

docs/README.md
i18n/zh/docusaurus-plugin-content-docs/current/README.md
versioned_docs/version-v1.0.0/README.md

/kind bug
fix
resolve https://github.com/karmada-io/website/issues/96

fix routing duplicate on npm run start

---

docs/casestudies/working-with-velero.md

[docs] improve working-with-velero.md

---

docs/casestudies/working-with-prometheus.md

Signed-off-by: windsonsea <haifeng.yao@daocloud.io>
Improve docs

Improve working-with-prometheus.md

---

src/components/button.js
src/pages/index.js

/kind cleanup
components must be in their own folder
resolve https://github.com/karmada-io/website/issues/100

replace Button to components

---

docs/getting-started/introduction.md

/kind cleanup
Now on the introduction page, "[install Karmada](https://karmada.io/zh/docs/install)." leads to a 404 page.
This PR fixes the path right.

improve introduction markdown content

---

src/components/whatIs.js
src/pages/index.js

/kind cleanup
components must be in their own folder
resolve https://github.com/karmada-io/website/issues/102

replace WhatIs to components

---

docs/userguide/resource-propagating.md
versioned_docs/version-v1.0.0/userguide/resource-propagating.md

/kind cleanup
Two fixes in [resource-propagating](https://karmada.io/docs/userguide/resource-propagating/)
- Url format error which caused invalid link in the first part of this document.
- Missed blank line which caused messed up description in 3rd point of [create-a-propagationpolicy-object](https://karmada.io/docs/userguide/resource-propagating/#create-a-propagationpolicy-object)
None
Local testes passed.

fix: messed up document

---

src/components/gitHubButton.js
src/pages/index.js

/kind cleanup
components must be in their own folder
resolve https://github.com/karmada-io/website/issues/112

replace github btn to components

---

docs/getting-started/architecture.md

[docs] updated /getting-started/architecture.md

---

docs/installation/install-kubectl-karmada.md

Signed-off-by: suxiang <suxiang@asiainfo.com>
Tell new user download right kubectl-karmada package.
Fixes https://github.com/karmada-io/karmada/issues/2336

Doc: add latest kubectl-karmada release suffix comment

---

docs/installation/install-binary.md
docs/installation/installation.md
docs/userguide/cicd/working-with-argocd.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-argocd.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/installation/install-binary.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/cicd/working-with-argocd.md
sidebars.js
versioned_docs/version-v1.3.0/installation/install-binary.md
versioned_docs/version-v1.3.0/installation/installation.md
versioned_docs/version-v1.3.0/userguide/cicd/working-with-argocd.md
versioned_sidebars/version-v1.3.0-sidebars.json

/kind cleanup
Add install-binary and fix some typos
Fixes #

add install-binary and fix some typos

---

README.md

/kind cleanup
docusaurus 2 is already in release
resolve https://github.com/karmada-io/website/issues/127

update docusaurus link

---

docs/administrator/configuration/configure-controllers.md
docs/administrator/upgrading/v0.10-v1.0.md
docs/administrator/upgrading/v1.1-v1.2.md
docs/userguide/cicd/working-with-flux.md
docs/userguide/network/working-with-submariner.md
docs/userguide/service/multi-cluster-ingress.md
docs/userguide/service/working-with-istio-on-non-flat-network.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.10-v1.0.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.1-v1.2.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-flux.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-ingress.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-non-flat-network.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v0.10-v1.0.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v1.1-v1.2.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/cicd/working-with-flux.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/network/working-with-submariner.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/multi-cluster-ingress.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
versioned_docs/version-v1.3.0/administrator/configuration/configure-controllers.md
versioned_docs/version-v1.3.0/administrator/upgrading/v0.10-v1.0.md
versioned_docs/version-v1.3.0/administrator/upgrading/v1.1-v1.2.md
versioned_docs/version-v1.3.0/userguide/cicd/working-with-flux.md
versioned_docs/version-v1.3.0/userguide/network/working-with-submariner.md
versioned_docs/version-v1.3.0/userguide/service/multi-cluster-ingress.md
versioned_docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md

/kind cleanup
fix link error in docs and link articles to web pages whenever possible
Fixes #
None

fix link error

---

docs/administrator/migration/migration-from-kubefed.md
sidebars.js
versioned_docs/version-v1.3.0/administrator/migration/migration-from-kubefed.md
versioned_sidebars/version-v1.3.0-sidebars.json

Since Kubefed is deprecating, it's time to provide migration guidelines.
Fixes #

Add migration path for Kubefed

---

docs/userguide/globalview/proxy-global-resource.md

Add user guide document for proxy.
Part of https://github.com/karmada-io/karmada/issues/2372

[docs] Add proxy user guide

---

docs/userguide/globalview/proxy-global-resource.md

Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>
Fixes #

change error from NotFound to MethodNotSupported

---

docs/administrator/configuration/configure-controllers.md

Signed-off-by: lonelyCZ <531187475@qq.com>
We introduce some new optional controllers to support to use `karmadactl register` to register member clusters with PULL mode.
Part of https://github.com/karmada-io/karmada/issues/2282
/cc @RainbowMango

Introduces the new optional controllers

---

docs/userguide/clustermanager/cluster-registration.md

Signed-off-by: lonelyCZ <531187475@qq.com>
Part of https://github.com/karmada-io/karmada/issues/2282
/cc @RainbowMango

Add a new way of registering cluster with PULL mode by CLI

---

docusaurus.config.js
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/proxy-global-resource.md
sidebars.js

/kind cleanup
This PR ensures we never ship any broken link by throwing an error.
https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks
https://docusaurus.io/docs/api/docusaurus-config#onBrokenMarkdownLinks
Fixes #

suprpress broken links

---

docs/userguide/scheduling/cluster-resources.md
docs/userguide/scheduling/propagate-dependencies.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/propagate-dependencies.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/scheduling/propagate-dependencies.md
sidebars.js
versioned_docs/version-v1.3.0/userguide/scheduling/propagate-dependencies.md

/kind feature
Add cluster resource models docs, refer to https://github.com/karmada-io/karmada/issues/2379.
Fixes #

add cluster resource models docs

---

package-lock.json

Signed-off-by: RainbowMango <qdurenhongcai@gmail.com>
/kind cleanup
This PR updates `tar` to version v6.1.9 to fix a security issue(`CVE-2021-37701`).
Fixes #
I updated the version by manual, is it right? Is there any better way to do this kind of thing?

Upgrade tar to version 6.1.9

---

docs/userguide/failover/failover.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/failover/failover.md
versioned_docs/version-v1.3.0/userguide/failover/failover.md

/kind feature
Update the failover document.
Part of https://github.com/karmada-io/karmada/issues/2281

update the failover document

---

docs/administrator/upgrading/README.md
docs/administrator/upgrading/v1.2-v1.3.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.2-v1.3.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/README.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v1.2-v1.3.md
sidebars.js
versioned_docs/version-v1.3.0/administrator/upgrading/README.md
versioned_docs/version-v1.3.0/administrator/upgrading/v1.2-v1.3.md
versioned_sidebars/version-v1.3.0-sidebars.json

Add upgrade document for upgrading from 1.2 to 1.3.
Fixes #

add upgrade document for upgrading from 1.2 to 1.3

---

docs/userguide/scheduling/cluster-resources.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/cluster-resources.md

Add resource model docs in Chinese
Fixes #
None

Add resource model docs in Chinese

---

adopters/README.md
docs/casestudies/adopters.md
i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
sidebars.js

Add adopters page for Karmada
Fixes #

Add adopters for Karmada

---

docs/userguide/failover/failover.md
docs/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/failover/failover.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/scheduling/resource-propagating.md
versioned_docs/version-v1.3.0/userguide/failover/failover.md
versioned_docs/version-v1.3.0/userguide/scheduling/resource-propagating.md

Signed-off-by: jwcesign [jiangwei115@huawei.com](mailto:jiangwei115@huawei.com)
What type of PR is this?
Fix doc format
What this PR does / why we need it:
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:

Fix doc format

---

docusaurus.config.js

/kind feature
This PR added [search](https://docusaurus.io/docs/search) to the website.
Fixes #

Enable documentation search

---

package-lock.json
package.json
src/components/featuresList.js
src/pages/index.js

/kind cleanup
resolve https://github.com/karmada-io/website/issues/168

remove unnecessary dependencies

---

docs/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/configuration/configure-controllers.md
versioned_docs/version-v1.3.0/administrator/configuration/configure-controllers.md

This PR added 3 controllers that introduced at v1.3 to https://karmada.io/docs/administrator/configuration/configure-controllers#karmada-controllers.
- federatedResourceQuotaSync
- federatedResourceQuotaStatus
- gracefulEviction
Fixes #

Add missed controllers

---

docs/casestudies/adopters.md
i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md

Add youzan to karmada adopters.
Fixes #

Add youzan to karmada adopters

---

docs/userguide/service/working-with-istio-on-non-flat-network.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/working-with-istio-on-non-flat-network.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md
versioned_docs/version-v1.3.0/userguide/service/working-with-istio-on-non-flat-network.md

https://github.com/karmada-io/karmada/pull/2293 seems missing in our docs.
Fixes #
/cc @zirain

Update istio-on-nonflat-network docs

---

docs/casestudies/adopters.md
i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md

Add Trip.com to karmada adopters
Fixes #

add trip.com to karmada adopters

---

docs/casestudies/adopters.md

Update adopters add new company.

Update adopters add new company.

---

docs/installation/install-binary.md
docs/resources/installation/install-binary/generate_cert/csr_config/admin.conf
docs/resources/installation/install-binary/generate_cert/csr_config/etcd/apiserver-etcd-client.conf
docs/resources/installation/install-binary/generate_cert/csr_config/etcd/healthcheck-client.conf
docs/resources/installation/install-binary/generate_cert/csr_config/etcd/peer.conf
docs/resources/installation/install-binary/generate_cert/csr_config/etcd/server.conf
docs/resources/installation/install-binary/generate_cert/csr_config/front-proxy-client.conf
docs/resources/installation/install-binary/generate_cert/csr_config/karmada.conf
docs/resources/installation/install-binary/generate_cert/csr_config/kube-apiserver.conf
docs/resources/installation/install-binary/generate_cert/csr_config/kube-controller-manager.conf
docs/resources/installation/install-binary/generate_cert/generate_ca.sh
docs/resources/installation/install-binary/generate_cert/generate_etcd.sh
docs/resources/installation/install-binary/generate_cert/generate_leaf.sh
docs/resources/installation/install-binary/generate_cert/util.sh
docs/resources/installation/install-binary/other_scripts/check_status.sh
docs/resources/installation/install-binary/other_scripts/create_kubeconfig_file.sh

Signed-off-by: raymondmiaochaoyue <raymondmiaochaoyue@didiglobal.com>
**1) First letter of words in title should be upper case.**
Exception: I keep "etcd" case the same as etcd official document, so it is not upper case.
**2) Change certificate generation code to 3 scripts and some configuration files.**
By looking at csr_config directory's contents, Users can easily find out what leaf certificates will generate. And modification of certificates is much easier than modification of one super long line of code. 
The original tls certificates generation logic has numerous problem, this commit fixes them. For example:
1. There is only 1 CA, rather than kubernetes recommended 3 CA. [PKI certificates and requirements](https://kubernetes.io/docs/setup/best-practices/certificat …

modify install-binary.md

---

docs/installation/install-binary.md
docs/resources/installation/install-binary/other_scripts/check_status.sh
docs/userguide/scheduling/scheduler-estimator.md

Signed-off-by: raymondmiaochaoyue <raymondmiaochaoyue@didiglobal.com>
Make install-binary.md cover more Karmada components.
This also provides user guide document for <https://github.com/karmada-io/karmada/pull/2574>
None
None

Add more sections to install-binary.md

---

docs/casestudies/adopters.md

Signed-off-by: wuyingjun <wuyingjun_yewu@cmss.chinamobile.com>
Fixes #
NONE
@RainbowMango @Poor12

add ecloud to karmada adopters

---

docs/installation/install-karmadactl.md
docs/installation/install-kubectl-karmada.md
docs/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/install-karmadactl.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/install-kubectl-karmada.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
sidebars.js

/kind cleanup
Distinguish karmadactl and kubectl-karmada
Fixes #
None

Distinguish karmadactl and kubectl-karmada

---

i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/troubleshooting.md

translation-docusaurus-plugin-content-docs/current/troubleshooting

---

docs/releases.md
i18n/zh/docusaurus-plugin-content-docs/current/releases.md
sidebars.js

Add release docs

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-filebeat.md

[zh] sync/administrator/monitoring/working-with-filebeat.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus.md

[zh] sync/administrator/monitoring/working-with-prometheus.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md

[zh] sync/administrator/backup/working-with-velero.md

---

i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md

Added zh text to this file:
```
i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
```

[zh] sync faq.md

---

i18n/zh/docusaurus-plugin-content-docs/current/installation/install-cli-tools.md

Added zh text to this page:
```
i18n/zh/docusaurus-plugin-content-docs/current/installation/install-cli-tools.md
```

[zh] sync /installation/install-cli-tools.md

---

i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md

```
i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
```
cc @Poor12

[zh] sync contribute-docs.md

---

docs/userguide/service/multi-cluster-ingress.md
docs/userguide/service/multi-cluster-service.md

/kind cleanup
Modify some problems in the document, while optimizing steps, the original library [karmada](https://github.com/karmada-io/karmada) has been merged, not synchronized to the library
Fixes #

Modify the multi-cluster Service discovery and multi-cluster ingress documents

---

blog/2022-09-06-karmada-v1.3/karmada-v1.3.md

Add blog `karmada-v1.3`

---

docs/userguide/service/multi-cluster-ingress.md
docs/userguide/service/multi-cluster-service.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-ingress.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-service.md

As talk in https://github.com/karmada-io/karmada/issues/2460#issuecomment-1238836360 and https://github.com/karmada-io/karmada/issues/2657, we need to add some notes to help users better experience the MCS feature.
Fixes #
/cc @631068264

Add note for mcs document: kubernetes version and pod/service CIDRs

---

docs/userguide/failover/failover-analysis.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-analysis.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/failover/failover.md
versioned_docs/version-v1.3.0/userguide/failover/failover.md

/kind cleanup
Fix typo in failover
Fixes #
None

Fix typo in failover

---

docs/userguide/clustermanager/cluster-registration.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md

Add document for [ClusterID](https://github.com/karmada-io/karmada/tree/master/docs/proposals/clusterid).
Fixes #

Add document for ClusterID

---

blog/2022-03-22-multi-cluster-management-with-an-ocean-of-nodes/index.md

/kind cleanup
Fix typo in blog
Fixes #
None

Fix typo in blog

---

docs/userguide/scheduling/override-policy.md

Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
Add docs for LabelsOverrider/AnnotationsOverrider
Fixes https://github.com/karmada-io/karmada/issues/2641

Add docs for LabelsOverrider/AnnotationsOverrider

---

i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md

Added zh text to this file:
```
i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
```
cc @Poor12

[zh] sync install-binary.md

---

i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md

Added zh text to this page:
```
i18n/zh/docusaurus-plugin-content-docs/current/casestudies/adopters.md
```
cc @Poor12

[zh] sync /casestudies/adopters.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus-in-control-plane.md

```
i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus-in-control-plane.md
```
cc @Poor12

[zh] sync working-with-prometheus-in-control-plane.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md

Added zh text to this page:
```
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/README.md
```
cc @Poor12

[zh] sync /administrator/upgrading/README.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.8-v0.9.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.9-v0.10.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.2-v1.3.md

Added zh text to 3 files:
```
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.8-v0.9.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.9-v0.10.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.2-v1.3.md
```
/cc @Poor12

[zh] sync 3 files in /upgrading

---

docs/administrator/configuration/configure-controllers.md

Signed-off-by: lonelyCZ <chengzhe@zju.edu.cn>
Fixes #
/cc @RainbowMango

Add configuring `certRotation` controller

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.10-v1.0.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.0-v1.1.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.1-v1.2.md

```
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v0.10-v1.0.md
```
/cc @Poor12

[zh] sync files in /upgrading

---

docs/userguide/security-governance/working-with-kyverno.md

Reform the docs and note that release-1.7 does not work for Karmada.
Fixes https://github.com/karmada-io/karmada/issues/2459

Improve kyverno docs

---

i18n/zh/docusaurus-plugin-content-docs/current/contributor/lifted.md

```
i18n/zh/docusaurus-plugin-content-docs/current/contributor/lifted.md
```
/cc @Poor12

[zh] sync /contributor/lifted.md

---

blog/2022-10-26-test-report/index.md
docs/developers/performance-test-setup-for-karmada.md
i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md

Signed-off-by: Phil-sun <sunxh0000@163.com>
What type of PR is this?
/kind cleanup
What this PR does / why we need it:
Fix format error in performance setup for Karmada. It may confuse users when they paste from docs.
Which issue(s) this PR fixes:
Fixes #

Fix format error

---

OWNERS
docs/OWNERS
i18n/OWNERS

/kind cleanup
This PR nominates @Poor12 and @Tingtal onto the owner list, they have been contributing a lot recently. 
Fixes #

Nominate Poor12 and Tingtal as docs owners

---

docs/troubleshooting/troubleshooting.md
i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/troubleshooting.md

Since this was a high frequency issue, so I think we need to add it to the Troubleshooting.
Fixes #

Add troubleshooting for x509 error when install karmada

---

docs/userguide/network/working-with-submariner.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md

/i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md
/cc @Poor12

[zh]userguide/network/working-with-submariner.md

---

docs/troubleshooting/troubleshooting.md

Add troubleshooting guide about "too many open files".
Fixes #
/cc @jwcesign

Add troubleshooting about "too many open files"

---

docs/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md

Update karmadactl init output
Fixes #none
@Poor12

Update karmadactl init output

---

docs/tutorials/crd-application.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md
sidebars.js

Add tutorial about how to propagate crd applications.
Fixes #
None

Add crd application tutorial

---

docs/installation/install-binary.md
docs/userguide/failover/failover-overview.md
docs/userguide/scheduling/cluster-resources.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-overview.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/cluster-resources.md

Evolute the reset feature gate to Beta.
Fixes #
None

Evolute the reset feature gate to Beta

---

i18n/zh/docusaurus-plugin-content-docs/current/get-started/nginx-example.md

```
i18n/zh/docusaurus-plugin-content-docs/current/get-started/nginx-example.md
```
/cc @Poor12

[zh] sync /get-started/nginx-example.md

---

docs/reference/karmadactl/karmadactl-usage-conventions.md
docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-usage-conventions.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

/kind feature
Update doc of `customizing-resource-interpreter.md` for declarative configuration.
Fixes #
```
update docs of customizing resource interpreter for declarative
```

update docs of customizing resource interpreter for declarative

---

docs/reference/karmadactl/karmadactl-usage-conventions.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-usage-conventions.md
sidebars.js

/kind cleanup
add sidebar for upgrade document form-v1.3-to-v1.4.
Fixes #
```
NONE
```

Add sidebar for upgrade 1.3-to-1.4

---

docs/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/resource-propagating.md
versioned_docs/version-v1.4.0/userguide/scheduling/resource-propagating.md

update document with resource-propagating.md

---

docs/key-features/features.md
docs/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/key-features/features.md
versioned_docs/version-v1.4.0/key-features/features.md

Refacter resource propagation
Fixes #

Refacter resource propagation

---

docs/developers/releasing.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/releasing.md

Signed-off-by: jwcesign <jiangwei115@huawei.com>
/kind cleanup
* Fix releasing.md font
Fixes #none

Fix releasing.md font

---

docs/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md
versioned_docs/version-v1.4.0/userguide/scheduling/override-policy.md

/kind cleanup
In the section of the override rules, two colons are missing
Fixes #

Supplement missing colon.

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/globalview/customizing-resource-interpreter.md
versioned_docs/version-v1.4.0/userguide/globalview/customizing-resource-interpreter.md

update document for Built-in Interpreter.
Fixes #

update document for Built-in Interpreter

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

Signed-off-by: chaunceyjiang <chaunceyjiang@gmail.com>
https://github.com/karmada-io/karmada/pull/3009
Fixes #

built-in interpreter support statefulset

---

docs/administrator/monitoring/working-with-prometheus-in-control-plane.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/monitoring/working-with-prometheus-in-control-plane.md

Add prometheus config for karmada-controller-manager
Fixes #
None

Add prometheus config for karmada-controller-manager

---

docs/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md
versioned_docs/version-v1.3.0/userguide/scheduling/override-policy.md
versioned_docs/version-v1.4.0/userguide/scheduling/override-policy.md

Signed-off-by: fsl <1171313930@qq.com>
Fixes #291

updaete override-policy.md

---

i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/namespace-management.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/bestpractices/namespace-management.md

fix typo of translate

---

docs/developers/customize-karmada-scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md

Add multiple scheduler docs
Part of https://github.com/karmada-io/karmada/issues/3024

Add multiple scheduler docs

---

i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

Ttranslate custom resource interpreter

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

/kind cleanup
For better reading and understanding, add ResourceInterpreterCustomization yaml example.
Fixes #

add ResourceInterpreterCustomization yaml example

---

docs/troubleshooting/trouble-shooting.md
i18n/zh/docusaurus-plugin-content-docs/current/troubleshooting/trouble-shooting.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/troubleshooting/troubleshooting.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/troubleshooting/trouble-shooting.md
versioned_docs/version-v1.3.0/troubleshooting/troubleshooting.md
versioned_docs/version-v1.4.0/troubleshooting/trouble-shooting.md

/kind cleanup
This PR migrate from k8s.gcr.io to registry.k8s.io
Fixes  https://github.com/kubernetes/k8s.io/issues/4780 
This fix is a part of the Umbrella issue https://github.com/kubernetes/k8s.io/issues/4780

Migrate from k8s.gcr.io to registry.k8s.io

---

docusaurus.config.js

/kind cleanup
Change theme to github
Fixes #
None

Change theme to github

---

docs/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4.0/userguide/scheduling/override-policy.md
versioned_docs/version-v1.4.0/userguide/scheduling/override-policy.md

updaete override-policy fieldSelector

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

add CronJob to build-in AggregateStatus Interpreter

---

docs/developers/document-releasing.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
sidebars.js

Add document release docs
Fixes #
None

Add document release docs

---

docs/developers/document-releasing.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md

/kind cleanup
In the process of handling #323, some improvements were found. Modify some specific operations to make the steps more correct.
Fixes #

update documentation releasing

---

docs/developers/customize-karmada-scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/customize-karmada-scheduler.md
versioned_docs/version-v1.5/developers/customize-karmada-scheduler.md

/kind cleanup
Fix filter interface when customize the scheduler. We have updated the filter interface since v1.5.
Fixes https://github.com/karmada-io/karmada/issues/3277

Fix filter interface when customize the scheduler

---

src/css/custom.css

/kind design
Fixes https://github.com/karmada-io/website/issues/326
After fix

update Supporters list

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

add pod to Built-in InterpretHealth Interpreter
Fixes #

update doc of built-in Interpreter

---

docs/userguide/bestpractices/unified-auth.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/unified-auth.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/bestpractices/unified-auth.md
versioned_docs/version-v1.5/userguide/bestpractices/unified-auth.md

/kind cleanup
As analyzed in https://github.com/karmada-io/karmada/issues/1961#issuecomment-1152106332, we now need to manually create a token for tom, so that we can continue testing.
Fixes #

update get token with tom in unified-auth.md

---

docs/core-concepts/introduction.md

Signed-off-by: [JadeFlute0127] [1635468471@qq.com]
**What this PR does / why we need it:**
add killercoda url for docs
**Which issue(s) this PR fixes:**
Part of https://github.com/karmada-io/playground/issues/1
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
```
NONE

add killercoda url for docs

---

i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md

Signed-off-by: [JadeFlute0127] [1635468471@qq.com]
**What this PR does / why we need it:**
update Chinese version for started with killercoda
**Which issue(s) this PR fixes:**
Part of https://github.com/karmada-io/playground/issues/1
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
```
NONE

update Chinese version for started with killercoda

---

docs/developers/customize-karmada-scheduler.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/customize-karmada-scheduler.md
versioned_docs/version-v1.5/developers/customize-karmada-scheduler.md

/kind cleanup
fix redundance kubectl.
Fixes #

fix redundance kubectl.

---

docs/userguide/failover/application-failover.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md
sidebars.js

Add application failover doc
Fixes #
None

Add application failover doc

---

docs/userguide/clustermanager/cluster-registration.md

/kind cleanup
Now the multi installation can support for register command, so update the doc note.
Fixes #
/cc @RainbowMango @calvin0327 @Poor12

Update the Note of register doc to support general installation

---

docs/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/scheduling/resource-propagating.md
versioned_docs/version-v1.5/userguide/scheduling/resource-propagating.md

Add document for ClusterAffinities introduction
Fixes #

Add document for ClusterAffinities introduction

---

docs/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md

Add karmada operator in installation.
Fixes #
None

Add karmada operator in installation

---

docs/reference/glossary.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/glossary.md
sidebars.js

Add glossary for Karmada
Fixes #
None

Add glossary for Karmada

---

i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md

- Sync Documents
none
Sync en docs to zh

[zh]update installation.md

---

i18n/zh/docusaurus-plugin-content-docs/current/casestudies/ci123.md
i18n/zh/docusaurus-plugin-content-docs/current/casestudies/daocloud.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3/casestudies/ci123.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4/casestudies/ci123.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/casestudies/ci123.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/casestudies/daocloud.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/casestudies/ci123.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/casestudies/daocloud.md

/kind cleanup
多云案例文章修复排版内容.
Fixes #

多云案例文章修复排版内容.

---

docs/userguide/service/working-with-eriecanal.md
versioned_docs/version-v1.6/userguide/service/working-with-eriecanal.md

/kind cleanup
Fix typo for ErieCanal.
Fixes #

Fix typo for ErieCanal.

---

i18n/zh/code.json

Signed-off-by: samzong.lu <samzong.lu@gmail.com>
/kind design
Optimize the system prompts of Chinese pages.
Fixes #

update Chinese code

---

docs/reference/glossary.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/glossary.md

/kind cleanup
Fix bullets alignment, which shall indent 2 spaces for an unordered list.

Fix indentations in en/zh glossary

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/backup/working-with-velero.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/reserved-namespaces.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md

translate crd-application.md

---

docs/core-concepts/concepts.md
i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/core-concepts/concepts.md
versioned_docs/version-v1.6/core-concepts/concepts.md

By default, the header should be continuous.
Fixes #
Fix title header error

Fix title header error

---

docs/developers/performance-test-setup-for-karmada.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/performance-test-setup-for-karmada.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4/developers/performance-test-setup-for-karmada.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/developers/performance-test-setup-for-karmada.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/developers/performance-test-setup-for-karmada.md
versioned_docs/version-v1.4/developers/performance-test-setup-for-karmada.md
versioned_docs/version-v1.5/developers/performance-test-setup-for-karmada.md
versioned_docs/version-v1.6/developers/performance-test-setup-for-karmada.md

fix typo CLusterLoader2
Fixes #

fix typo CLusterLoader2

---

i18n/OWNERS

Request to join the maintenance work for the i18n documentation.
Fixes #
forget join the i18n/owners.

Request to join the i18n OWNER

---

i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/concepts.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/core-concepts/concepts.md

[zh] translate concepts.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/promote-legacy-workload.md

Translate promote-legacy-workload.md

---

docs/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/administrator/configuration/configure-controllers.md
versioned_docs/version-v1.6/administrator/configuration/configure-controllers.md

Add applicationFailover and federatedHPA to controllers
Fixes #
None

Add applicationFailover and federatedHPA to controllers

---

i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/architecture.md
i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md

translate translate all core-concepts docs.
- i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md
- i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/architecture.md
Fixes #

[zh] translate all core-concepts docs.

---

docs/userguide/autoscaling/federatedhpa.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/federatedhpa.md

translate federatedhpa.md

---

.github/ISSUE_TEMPLATE/request-doc.md

/kind cleanup
This PR introduced an [issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) for tracking missing documents.
With this template, we can track doc tasks and call for help from the community.
Fixes #

Add issue template for tracking missing documents

---

docs/administrator/migration/migration-from-kubefed.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migration-from-kubefed.md

[zh]translate docs:migration-from-kubefed.md

---

i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md

translate configure-controllers.md

---

i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/aggregated-api-endpoint.md

Add one of the following kinds:

[zh] translate docs: aggregated-api-endpoint.md

---

docs/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/scheduling/resource-propagating.md
versioned_docs/version-v1.4/userguide/scheduling/resource-propagating.md
versioned_docs/version-v1.5/userguide/scheduling/resource-propagating.md
versioned_docs/version-v1.6/userguide/scheduling/resource-propagating.md

Add description for priority of pp and cpp
Fixes #422 
None

Add description for priority of pp and cpp

---

docs/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md

doc: update Karmada controller list

---

i18n/zh/docusaurus-plugin-content-docs/current/contributor/count-contributions.md

translate  docs
1./i18n/zh/docusaurus-plugin-content-docs/current/contributor/count-contributions.md 
Fixes #

[zh] translate count-contributions docs

---

package-lock.json

/kind cleanup
Update package-lock.json after upgrading dependencies
Fixes #

Update package-lock.json after upgrading dependencies

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

Adding ingress to interpret dependency.
Fixes #439
I have added ingress to interpret dependency if there are any other changes or corrections then notify accordingly

added ingress to interpret dependency

---

docs/userguide/globalview/customizing-resource-interpreter.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md

Changes made:
- Added `Pod(v1)` to the InterpretReplica support list in https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#interpretreplica
Fixes #451

docs: add pod to InterpretReplica support list

---

docs/administrator/configuration/configure-controllers.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/configure-controllers.md

/kind feature
Refer to https://github.com/karmada-io/karmada/issues/3916
Part of https://github.com/karmada-io/karmada/issues/3916

enable clusterrole-aggregation controller

---

docs/administrator/upgrading/v1.6-v1.7.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.6-v1.7.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.7/administrator/upgrading/v1.6-v1.7.md
sidebars.js
versioned_docs/version-v1.7/administrator/upgrading/v1.6-v1.7.md
versioned_sidebars/version-v1.7-sidebars.json

doc: add Upgrading Instruction for v1.6 to v1.7
Fixes #

doc: add Upgrading Instruction for v1.6 to v1.7

---

versioned_sidebars/version-v1.7-sidebars.json

/kind bug
missed to update sidebar for migration doc
Fixes #
@RainbowMango

fix: missed to update sidebar for migration doc

---

docs/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
docs/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
docs/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
docs/reference/karmada-api/common-definitions/delete-options.md
docs/reference/karmada-api/common-definitions/label-selector.md
docs/reference/karmada-api/common-definitions/list-meta.md
docs/reference/karmada-api/common-definitions/node-selector-requirement.md
docs/reference/karmada-api/common-definitions/object-meta.md
docs/reference/karmada-api/common-definitions/patch.md
docs/reference/karmada-api/common-definitions/quantity.md
docs/reference/karmada-api/common-definitions/status.md
docs/reference/karmada-api/common-definitions/typed-local-object-reference.md
docs/reference/karmada-api/common-parameter/common-parameters.md
docs/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
docs/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
docs/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
docs/reference/karmada-api/work-resources/work-v1alpha1.md
sidebars.js

add api documents
part of https://github.com/karmada-io/karmada/issues/4090
@XiShanYongYe-Chang @RainbowMango 
[Quick Preview](https://deploy-preview-476--karmada.netlify.app/docs/next/reference/api-documents/cluster-resources/cluster-v1alpha1)
If you want to generate api document, you can do like this:
1) update [`api/v1.7/swagger.json`] and [`config/v1.7/toc.yaml`] in [reference-docs](https://github.com/chaosi-zju/reference-docs). (temporary plan, to be adjusted after holidays)
~2. clone this latest version repo, run `bash reference-api.sh` in a linux machine.~ (I cancelled submitting this script)
2) run following commands to …

Add API Documents

---

sidebars.js

auto generate index at sidebar for karmada-api
Fixes #

auto generate index at sidebar for karmada-api

---

i18n/zh/docusaurus-plugin-content-docs/current.json
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/delete-options.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/label-selector.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/list-meta.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/node-selector-requirement.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/object-meta.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/patch.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/quantity.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/status.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/typed-local-object-reference.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-parameter/common-parameters.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/work-v1alpha1.md

Before we start translating Karmada API documents #483 , we need to add related files to the `zh` directory so that others can directly translate Chinese documents.
Fixes #

prepare for Karmada API document translate

---

i18n/zh/docusaurus-plugin-content-docs/current.json
sidebars.js

/kind feature
Translate Karmada API index description
Part of #483 

Translate Karmada API index description

---

docs/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md

Some people often ask why the CRD resource of the Cluster cannot be found. Therefore, the explanation of this problem is included in the FAQ.
Fixes #

Add cluster API resource faq

---

docs/tutorials/autoscaling-with-resource-metrics.md
docs/userguide/autoscaling/federatedhpa.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/autoscaling/federatedhpa.md
sidebars.js

/kind cleanup
It's unclear in FederatedHPA docs.
Fixes #none
none

doc: FederatedHPA docs cleanup

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/work-v1alpha1.md

translate API work resource
Part of #483 

translate api work resource

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md

translate API policy resource
Part of #483

translate api policy resource

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md

Translate API auto-scaling resource
Part of #483 

translate api auto scaling resource

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/cluster-resources/cluster-v1alpha1.md

translate API cluster resource
Part of #483

translate api cluster resource

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/search-resources/resource-registry-v1alpha1.md

Translate API search resource
Part of #483

translate api search resource

---

docusaurus.config.js

resolve https://github.com/karmada-io/website/issues/495

Accessibility add links name to icons

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md

/kind cleanup
fix wrong translation of referent word in auto-scaling-resources
Fixes #

fix wrong translation of referent word in auto-scaling-resources

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md

translate api config resource
Part of #483 

translate api config resource

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/delete-options.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/label-selector.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/list-meta.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/node-selector-requirement.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/object-meta.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/patch.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/quantity.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/status.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/typed-local-object-reference.md

Translate API with common definitions
Part of #483

translate api with common definitions

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-parameter/common-parameters.md

translate api with common parameter

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md

Translate API networking resource
Fixes #483

translate api networking resource

---

i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md

replace the invalid link with a valid one in webside
Fixes 

fix: fix the invalid link in doc

---

docs/administrator/configuration/resource-deletion-protection.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/resource-deletion-protection.md
sidebars.js

add the user guide for resource deletion protection
Part of https://github.com/karmada-io/karmada/issues/3728

Add resource deletion protection user guide

---

README.md

remove unnecessary docusaurus version in README.md

---

docs/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md

Add faq to explain `How to prevent automatic propagation of Namespace to all member clusters?`
Fixes #

Add namespace sync FQA

---

docs/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/current/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/faq/faq.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.7/faq/faq.md
versioned_docs/version-v1.3/faq/faq.md
versioned_docs/version-v1.4/faq/faq.md
versioned_docs/version-v1.5/faq/faq.md
versioned_docs/version-v1.6/faq/faq.md
versioned_docs/version-v1.7/faq/faq.md

/kind bug
/kind cleanup
Fixes #

Fix break link in FAQ

---

docs/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md

Translate karmada search doc
Fixes #

Translate karmada search document

---

i18n/zh/docusaurus-plugin-content-docs/current.json

Translate sibebar items.
Fixes #

Translate sibebar items

---

docs/administrator/upgrading/v1.7-v1.8.md
docusaurus.config.js
sidebars.js
versioned_docs/version-v1.8/administrator/upgrading/v1.7-v1.8.md
versioned_sidebars/version-v1.8-sidebars.json

add Upgrading Instruction for v1.7 to v1.8
Fixes #
CC @XiShanYongYe-Chang @jwcesign @zhzhuang-zju do you have any suggest to add into `Upgrading Instruction`

add Upgrading Instruction for v1.7 to v1.8

---

docs/key-features/features.md
i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md

/kind cleanup
/kind bug
Repair broken links and use relative paths to locate resources.
Fixes #

Repair broken links and use relative paths to locate resources

---

docusaurus.config.js
i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.7-v1.8.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.8/administrator/upgrading/v1.7-v1.8.md

add zh Upgrading Instruction for v1.7 to v1.8
Fixes #

add zh Upgrading Instruction for v1.7 to v1.8

---

docs/contributor/count-contributions.md
i18n/zh/docusaurus-plugin-content-docs/current/contributor/count-contributions.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/contributor/count-contributions.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.7/contributor/count-contributions.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.8/contributor/count-contributions.md
versioned_docs/version-v1.6/contributor/count-contributions.md
versioned_docs/version-v1.7/contributor/count-contributions.md
versioned_docs/version-v1.8/contributor/count-contributions.md

Fix wrong reference website for docs.
Fixes #
NONE

Fix wrong reference website for docs.

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/instrumentation/event.md

add zh doc to karmada event reference
Fixes #

add zh doc to karmada event reference

---

docs/core-concepts/introduction.md
i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/introduction.md
src/pages/index.js

doc: Update sandbox to incubation
Fixes #none
none

doc: Update sandbox to incubation

---

docs/userguide/globalview/customizing-resource-interpreter.md

add doc about karmada retain interpreter common problems
Fixes #

add doc about karmada retain interpreter common problems

---

.dockerignore
Dockerfile
Makefile
README.md
bs-config.js
package-lock.json
package.json
start-watch.sh

Signed-off-by: samzong.lu <samzong.lu@gmail.com>
/kind feature
a simple way to preview locally using Docker. With just one command, you can easily achieve this.
Fixes #181
Fixes #430

preview locally using Docker

---

netlify.toml

https://docusaurus.io/blog/releases/3.0#breaking-changes
/kind feature

update node version for netlify

---

docs/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.4/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.5/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.6/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.7/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.8/installation/installation.md
versioned_docs/version-v1.3/installation/installation.md
versioned_docs/version-v1.4/installation/installation.md
versioned_docs/version-v1.5/installation/installation.md
versioned_docs/version-v1.6/installation/installation.md
versioned_docs/version-v1.7/installation/installation.md
versioned_docs/version-v1.8/installation/installation.md

Remove redundant content in the Installation Overview chapter.
https://github.com/karmada-io/website/blob/3406bf0dc9600dce974c3b80dcb85315685c1ec2/docs/installation/installation.md?plain=1#L175-L179
https://github.com/karmada-io/website/blob/3406bf0dc9600dce974c3b80dcb85315685c1ec2/docs/installation/installation.md?plain=1#L202-L206
Fixes #
NONE

remove redundant content in the Installation Overview chapter

---

docs/userguide/network/working-with-submariner.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/network/working-with-submariner.md

/kind cleanup
There are some slight changes to the installation guide documentation.
Fixes #

Make some updation on work-with-submariner doc

---

blog/2022-10-26-test-report/index.md
docs/reference/karmada-api/common-definitions/quantity.md
docs/tutorials/access-service-across-clusters.md
i18n/zh/docusaurus-plugin-content-blog/2022-10-26-test-report/index.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-definitions/quantity.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.8/reference/karmada-api/common-definitions/quantity.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-with-resource-metrics.md
versioned_docs/version-v1.8/reference/karmada-api/common-definitions/quantity.md

/kind cleanup
fix typos error of documents
Fixes #

fix typos error of documents

---

i18n/zh/docusaurus-plugin-content-pages/adopters.md

Add JDCloud to adopters of zh

---

.github/workflows/typos.yml
docs/contributor/contribute-docs.md
i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
typos.toml

/kind flake
add typo check ci action to automacally check typo errors.
Fixes #

add typo check ci action

---

docs/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md

Add installing via operator to karmada search installation tutorials
Fixes #
NONE

Add installing via operator to karmada search installation tutorials

---

blog/2022-10-26-test-report/index.md
docs/contributor/contribute-docs.md
docs/installation/install-binary.md
docs/releases.md
i18n/zh/docusaurus-plugin-content-docs/current/releases.md

<!--
Add one of the following kinds:
/kind cleanup
/kind feature
Fixes #

update some docs for docusaurus v3

---

sidebars.js
versioned_sidebars/version-v1.9-sidebars.json

/kind bug
fix sidebar for Karmada v1.9 API Document
I am sorry that in PR #573,  I mistakenly wrote the `v1.9` version sidebar item into the `next` version sidebar file.
Fixes #

fix sidebar for Karmada v1.9 API Document

---

OWNERS

nominate windsonsea to the global reviewers

---

i18n/zh/docusaurus-plugin-content-docs/current/contributor/contribute-docs.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/crd-application.md

doc: fix nit bugs in chinese document

---

docs/tutorials/access-service-across-clusters.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/access-service-across-clusters.md
versioned_docs/version-v1.9/tutorials/access-service-across-clusters.md

According to the [comment](https://github.com/karmada-io/karmada/issues/4687#issuecomment-2114503889), we need to change the targetPort in the example to 80.
Fixes [#4687](https://github.com/karmada-io/karmada/issues/4687)

Change the targetPort in the example to 80

---

docs/tutorials/workload-rebalancer.md
sidebars.js

add tutorial for workload-rebalancer
Fixes part of https://github.com/karmada-io/karmada/issues/4840
[quick-click](https://deploy-preview-612--karmada.netlify.app/docs/next/tutorials/workload-rebalancer)

add tutorial for workload-rebalancer

---

i18n/zh/docusaurus-plugin-content-docs/current/installation/ha-installation-with-cli.md

translate zh/installation/ha-installation-with-cli

doc: translate zh/installation/ha-installation-with-cli

---

i18n/zh/docusaurus-plugin-content-docs/current/tutorials/workload-rebalancer.md

add zh tutorial for workload-rebalancer
Fixes part of https://github.com/karmada-io/karmada/issues/4840
[quick preview](https://deploy-preview-627--karmada.netlify.app/zh/docs/next/tutorials/workload-rebalancer)

add zh tutorial for workload-rebalancer

---

docs/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
docs/reference/karmada-api/common-parameter/common-parameters.md
docs/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/common-parameter/common-parameters.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
sidebars.js

update API reference docs of release-1.10

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.10/reference/karmada-api/remedy-resources/remedy-v1alpha1.md

translate remedy api
Parts of #633

translate remedy api

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.10/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
versioned_sidebars/version-v1.10-sidebars.json

translate WorkloadRebalancer api docs
Fixes #633 

translate WorkloadRebalancer api

---

i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/components.md

fix wrong url in zh docs components.md

---

i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md

translate zh/userguide/clustermanager/cluster-registration

doc: translate zh/userguide/clustermanager/cluster-registration

---

docs/administrator/security/verify-artifacts.md
docs/releases.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/verify-artifacts.md

SBOM has been added to Karmada's release assets, and the documentation describes the use of SBOM and how to use it.
Fixes #NONE
NONE

Add sbom to release assets

---

docs/userguide/scheduling/resource-propagating.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/resource-propagating.md

/kind bug
Update wrong yaml writing in Suspend and resume of resource propagation.
Fixes #

Update wrong yaml writing in Suspend and resume of resource propagation

---

docs/userguide/cicd/working-with-pipecd.md

/kind bug
I fixed some words mismatched with explained images
Follow #680 

Fix words mismatched with images

---

docs/userguide/failover/application-failover.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md

/kind feature
Add doc for stateful application failover, it is related to https://github.com/karmada-io/karmada/issues/5788
Fix #

Add doc for stateful application failover

---

docs/userguide/failover/application-failover.md
docs/userguide/failover/failover-overview.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/application-failover.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/failover-overview.md

/kind feature
Set Failover FeatureGate by default, it is related to https://github.com/karmada-io/karmada/pull/5899
Fixes #

Set Failover FeatureGate by default

---

docs/developers/document-releasing.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md

improve releasing doc

---

i18n/zh/docusaurus-plugin-content-blog/2025-01-17-karmada-security-audit/karmada-security-audit.md

publish karmada security audit result in Chinese
Fixes #

publish karmada security audit result in Chinese

---

docs/installation/installation.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.3/installation/installation.md
versioned_docs/version-v1.10/installation/installation.md
versioned_docs/version-v1.11/installation/installation.md
versioned_docs/version-v1.12/installation/installation.md
versioned_docs/version-v1.3/installation/installation.md
versioned_docs/version-v1.4/installation/installation.md
versioned_docs/version-v1.5/installation/installation.md
versioned_docs/version-v1.6/installation/installation.md
versioned_docs/version-v1.7/installation/installation.md
versioned_docs/version-v1.8/installation/installation.md
versioned_docs/version-v1.9/installation/installation.md

Fixes [#6080](https://github.com/karmada-io/karmada/issues/6080)
The update command initializes Karmada and customizes the directories for storing certificates and configuration files, avoiding issues related to insufficient permissions in system directories like /etc/karmada. for not root users

Updated Karmada installation documentation for non-root users

---

docs/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.10/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.11/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.12/tutorials/karmada-search.md
i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/karmada-search.md
versioned_docs/version-v1.10/tutorials/karmada-search.md
versioned_docs/version-v1.11/tutorials/karmada-search.md
versioned_docs/version-v1.12/tutorials/karmada-search.md
versioned_docs/version-v1.9/tutorials/karmada-search.md

fix: karmada operator field typo

---

docs/administrator/configuration/priority-class-configuration.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/configuration/priority-class-configuration.md
sidebars.js

add priority class configuration feature dos
Parts of #https://github.com/karmada-io/karmada/issues/6042

add priorityclass configuration feature dos

---

docs/developers/document-releasing.md
i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md

The API docs generator has been merged into the repository, and the document-releasing process can be further improved. 
Fixes #
NONE

improve document-releasing process

---

docs/administrator/security/security-considerations.md
i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/security-considerations.md

Karmada components provide users with listening addresses that can be configured for services such as business operations or health checks. To make it more convenient for users to centrally understand this configuration information, we have provided an explanation in the security considerations document.  
Fixes #

Add binding address configuration for security considerations

---

package-lock.json
package.json

update semi-ui to 2.77.1

---

docs/userguide/scheduling/override-policy.md
i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md

Add more description for op/cop resourceSelectors.
Fixes  https://github.com/karmada-io/karmada/issues/6103

add more description for op/cop resourceSelectors

---

i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/namespace-management.md

What type of PR is this?
What this PR does / why we need it:
Update `zh` namespace-management document.
Which issue(s) this PR fixes:
Fix #651 
Special notes for your reviewer:

Update namespace-management document

---

i18n/zh/docusaurus-plugin-content-docs/current/reference/karmadactl/karmadactl-config.v1alpha1.md

Supplement the Chinese version of the documentation of the configuration file used by karmadactl init
Fixes #

add chinese doc for karmadactl init config documents

---

package-lock.json
package.json

resolve https://github.com/karmada-io/website/issues/832

bump semi-ui

---

infra/gen-resourcesdocs/config/current/toc.yaml

update toc file according to the latest Karmada API resources
Parts of #844

update toc file according to the latest Karmada API resources

---

OWNERS

/kind cleanup
@windsonsea is the approver of i18n; he has been contributing to this project for years and has made a significant contribution.
This PR nominates @windsonsea as the approver of the website project to avoid blocking PRs like #824.
Fixes #

Nominate windsonsea as the approver

---

package-lock.json
package.json

update semi-ui to 2.83.0

---

package-lock.json
package.json

resolve https://github.com/karmada-io/website/issues/865

bump semi-ui to 2.84.0

---

src/data/supporters.js

Add new supporters

---

docs/administrator/upgrading/README.md
docs/administrator/upgrading/how-to-upgrade.md
sidebars.js

Add a guide outlines the process for upgrading Karmada, covering API and component updates, as well as support for upgrade methods like Helm and Operator.
Fixes #

add upgrade guide

---

i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/working-with-anp.md

Translate the document "Deploy ANP For Pull mode" from English to Chinese.
**Translate Repository File Path**
> website/i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/working-with-anp.md
**Key Details**
1. Translated Document Name: "Deploy ANP For Pull mode"
2. Translation Scope: Complete translation (full content of the original English document, no missing chapters/sections)
3. Additional Notes:
- No modifications/deletions to original technical content; only language conversion performed.

docs: translate “Deploy ANP For Pull mode” to Chinese

---

docs/reference/karmada-api/app-resources/workload-rebalancer-v1alpha1.md
docs/reference/karmada-api/auto-scaling-resources/cron-federated-hpa-v1alpha1.md
docs/reference/karmada-api/auto-scaling-resources/federated-hpa-v1alpha1.md
docs/reference/karmada-api/cluster-resources/cluster-v1alpha1.md
docs/reference/karmada-api/config-resources/resource-interpreter-customization-v1alpha1.md
docs/reference/karmada-api/config-resources/resource-interpreter-webhook-configuration-v1alpha1.md
docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md
docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md
docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/cluster-taint-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/federated-resource-quota-v1alpha1.md
docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md
docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md
docs/reference/karmada-api/remedy-resources/remedy-v1alpha1.md
docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md
docs/reference/karmada-api/work-resources/cluster-resource-binding-v1alpha2.md
docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md
docs/reference/karmada-api/work-resources/work-v1alpha1.md
infra/gen-resourcesdocs/Makefile

/kind cleanup
Update API reference docs to make it work with MDX v3.0+
Fixes #

update API reference
