docs/userguide/override-policy.md, sidebars.js, versioned_docs/version-v1.0.0/userguide/override-policy.md, versioned_sidebars/version-v1.0.0-sidebars.json
Signed-off-by: hanweisen <hanweisen_yewu@cmss.chinamobile.com>
The user guide of override-policy is missing. copy from karmada. I submit a PR https://github.com/karmada-io/karmada/pull/1896 move override-policy.md to userguide folder. If website will sync userguide from karmada with relsease 1.2. This PR should be closed.
Fixes #
=> [doc] sync override-policy.md from karmada

package-lock.json, yarn.lock
/kind cleanup
Upgrade async to version 2.6.4(the latest version).
To fix a security issues(CVE-2021-43138):
A vulnerability exists in Async through 3.2.1 for 3.x and through 2.6.3 for 2.x (fixed in 3.2.2 and 2.6.4), which could let a malicious user obtain privileges via the mapValues() method.
Fixes #
@Arhell I updated the version by manual, is it right?  Is there any better way to do this kind of thing?
=> Update async to version 2.6.4

docs/getting-started/core-concept.md
The original webpage is https://karmada.io/docs/getting-started/core-concept
Have a try to make it beautiful and official. 
Grammar and layout optimization
Not sure if all my changes are correct or not. Need your confirmation, thanks.
@rgrupesh @Arhell
=> [doc] optimize text and layout of core-concept.md

docs/troubleshooting.md
Signed-off-by: windsonsea <haifeng.yao@daocloud.io>
text and layout optimization, to make our doc official
Feel nice to learn native English from @rgrupesh @Arhell
=> [doc] text and layout optimization: docs/troubleshooting.md

i18n/zh/docusaurus-plugin-content-docs/version-v1.3.0/administrator/upgrading/v0.10-v1.0.md
/kind cleanup
When looking at the building logs, I can see the warning as follows:
```
5:03:39 PM: Exhaustive list of all broken links found:
5:03:39 PM: 
5:03:39 PM: - On source page path = /zh/docs/administrator/upgrading/v0.10-v1.0:
5:03:39 PM:    -> linking to ./multi-cluster-service.md (resolved as: /zh/docs/administrator/upgrading/multi-cluster-service.md)
```
This page is not exist:
https://karmada.io/zh/docs/administrator/upgrading/multi-cluster-service.md
Fixes #
@Arhell @rgrupesh I remember Docusaurus can deny broken links during the building phase, I think this feature was disabled by #31, I guess it's time to get the feature back, how do …
=> Fix broken links for v1.3.0

.gitignore
add build cachedir to .gitignore
Ignore the files generated by default build to prevent contributors from misoperations causing build files to be carried in PR; this is very friendly to new users.
=> update .gitignore to remove default generate  directory

i18n/zh/docusaurus-plugin-content-docs/current/userguide/service/multi-cluster-service.md
=> Add docs `userguide`

docs/userguide/clustermanager/working-with-anp.md
Signed-off-by: lonelyCZ <531187475@qq.com>
/kind cleanup
Fixes #
=> Optimize anp document

docs/administrator/monitoring/working-with-prometheus-in-control-plane.md
1. Give indentation to fix the alignment of ordered list
2. Removed `1.` when the **attention** block only includes an orphan comment
=> Fix alignment in working-with-prometheus-in-control-plane.md

docs/installation/install-binary.md, docs/userguide/scheduling/cluster-resources.md, docs/userguide/scheduling/propagate-dependencies.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/cluster-resources.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/propagate-dependencies.md
/kind failing-test
The PropagateDeps feautre hes been stably supported n multiple versions (since version v1.1). It is planned to enable the PropagateDeps FeatureGate by default and evolute it to beta.
Change association: https://github.com/karmada-io/karmada/pull/2875
Fixes #
```
karmada-controller-manager: evolute PropagateDeps FeatureGate to Beta  and enable it by default
```
=> evolute PropagateDeps FeatureGate to Beta and enable it by default

docs/userguide/globalview/customizing-resource-interpreter.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
Update documents as per https://github.com/karmada-io/karmada/pull/2997 which introduced a default interpreter(`AggregateStatus`) for `PodDisruptionBudget(policy/v1)`.
Fixes #287 
=> Update default resource interpreter documents for PodDisruptionBudget

docs/key-features/features.md, i18n/zh/docusaurus-plugin-content-docs/current/key-features/features.md
Signed-off-by:  justedennnnn  chenlu.li@daocloud.io
modify docs format
Fixes #
=> [zh]modify docs format

i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md
translate document releasing docs
1. i18n/zh/docusaurus-plugin-content-docs/current/developers/document-releasing.md 
Fixes #
=> [zh] translate document releasing docs

i18n/OWNERS
for karmada-io/community#39
I joined Karmada one year ago and have actively contributed to the project. By this time, I have [authored 24 PRs](https://github.com/karmada-io/website/pulls/windsonsea), and I have also [reviewed 17 PRs](https://github.com/karmada-io/website/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3A%40me).
Recently, with the increase in en-zh PRs, I have noticed that the review process is not always timely. To address this, I would like to take on the responsibility of improving the documentation, particularly for Chinese content, in order to provide convenience for native Chinese developers.
=> add windsonsea to doc-reviewers

docs/userguide/bestpractices/unified-auth.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/bestpractices/unified-auth.md
This PR specifies which `kubeconfig`  file to use in the step3 of the unified authentication to avoid any user confusion.
Fixes #437
=> Add kubeconfig in  unified auth

docs/administrator/verify-artifacts.md, i18n/zh/docusaurus-plugin-content-docs/current/administrator/verify-artifacts.md, sidebars.js
doc for cosign verify images.
Fixes #379 #448
Refer to https://github.com/karmada-io/karmada/issues/3435
@liangyuanpeng @RainbowMango @XiShanYongYe-Chang
=> add cosign verify images doc

i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/determine-cluster-failures.md
Improve format and fix typo of determine cluster failures
```
i18n/zh/docusaurus-plugin-content-docs/current/userguide/failover/determine-cluster-failures.md
```
No
=> [zh] Fix and improve determine cluster failures

docs/userguide/globalview/customizing-resource-interpreter.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.4/reference/karmadactl/karmadactl-usage-conventions.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.5/reference/karmadactl/karmadactl-usage-conventions.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.5/userguide/globalview/customizing-resource-interpreter.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.6/userguide/globalview/customizing-resource-interpreter.md, versioned_docs/version-v1.4/reference/karmadactl/karmadactl-usage-conventions.md, versioned_docs/version-v1.5/reference/karmadactl/karmadactl-usage-conventions.md, versioned_docs/version-v1.5/userguide/globalview/customizing-resource-interpreter.md, versioned_docs/version-v1.6/userguide/globalview/customizing-resource-interpreter.md
/kind cleanup
/kind bug
When a field of an object is empty, retrieving its value will yield nil:
An error will occur when using this nil value to index a table.
Therefore, we need to correct these mistakes in writing
we can test with the command
```shell
karmadactl interpret -f resource-interpreter-customization.yaml --operation interpretDependency --observed-file observed-deploy-nginx.yaml
```
<details>
<summary>observed-deploy-nginx.yam</summary>
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 3
paused: true
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- image: nginx
name: nginx
status:
availableReplicas: 2 …
```
=> Fix dependencies lua script bug

i18n/zh/docusaurus-plugin-content-docs/current/installation/installation.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.7/installation/installation.md
There is a typo error in installation doc (Chinese version), spell `--karmada-data` to `--karmada data`, this commit fixed this mistake
Fixes #
No
=> doc: fix typo error in --karmada-data params

i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/customizing-resource-interpreter.md
add zh doc to karmada retain interpreter common problems
explaining the existing problem about retain interpreter and how to do when the Karmada control plane has a control conflict with a member cluster.
Fixes #
[quick click](https://deploy-preview-539--karmada.netlify.app/zh/docs/next/userguide/globalview/customizing-resource-interpreter/)
=> add zh doc to karmada retain interpreter common problems

docs/installation/ha-installation-with-cli.md, sidebars.js
This PR introduces a guide for deploying Karmada HA using CLI.
Related to: #418
Task 2 out of 5
**Newly added page**: https://deploy-preview-453--karmada.netlify.app/docs/next/installation/ha-installation-with-cli
=> Add HA installation with CLI

docs/tutorials/access-service-across-clusters.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/access-service-across-clusters.md, versioned_docs/version-v1.9/tutorials/access-service-across-clusters.md
Add a note to enable the `Multi-Cluster Services` feature gate
Fixes #
=> Add a note to enable the Multi-Cluster Services feature gate

docs/userguide/globalview/proxy-global-resource.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/globalview/proxy-global-resource.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.9/userguide/globalview/proxy-global-resource.md, versioned_docs/version-v1.9/userguide/globalview/proxy-global-resource.md
Add more detailed instruction for global search.
Fixes https://github.com/karmada-io/karmada/issues/4678
=> Add more detailed instruction for global search

docs/developers/customize-karmada-scheduler.md, i18n/zh/docusaurus-plugin-content-docs/current/developers/customize-karmada-scheduler.md
Add ClusterEviction plugin description in `Developer Guide/Customize the scheduler` page.
Fixes https://github.com/karmada-io/karmada/issues/4803
=> Add ClusterEviction plugin

docs/developers/add-new-api.md, i18n/zh/docusaurus-plugin-content-docs/current/developers/add-new-api.md, sidebars.js
In order to avoid missing items when adding new APIs in the Karmada repo, resulting in extended development time, relevant check items are now added.
Fixes #
=> Add checklist for adding new API

docs/core-concepts/concepts.md, docs/key-features/features.md, versioned_docs/version-v1.3/faq/faq.md
DCO keeps failing despite the sign-off being included in the commit message.
Fix: after removing privacy option from github email, git cache had to be updated to reflect the changes.
=> Fix typos on docs

docs/faq/faq.md, docs/key-features/features.md, docs/userguide/clustermanager/cluster-registration.md
Also, green box should be fixed in here: (karamda instead of karmada)
=> Docs typo fixes

docs/tutorials/autoscaling-with-custom-metrics.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md
translate zh/tutorials/autoscaling-with-custom-metrics
=> doc: translate zh/tutorials/autoscaling-with-custom-metrics

docs/tutorials/access-service-across-clusters.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/access-service-across-clusters.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-workload-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/autoscaling-workload-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.8/tutorials/autoscaling-workload-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/autoscaling-federatedhpa-with-cronfederatedhpa.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.9/tutorials/autoscaling-workload-with-cronfederatedhpa.md
translate zh/tutorials/access-service-across-clusters
=> doc: translate zh/tutorials/access-service-across-clusters

docs/userguide/scheduling/workload-rebalancer.md, sidebars.js
/kind feature
add userguide for workload-rebalancer
Fixes part of https://github.com/karmada-io/karmada/issues/4840
[quick click](https://deploy-preview-608--karmada.netlify.app/docs/next/userguide/scheduling/workload-rebalancer)
=> add userguide for workload-rebalancer

i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/workload-rebalancer.md
add zh userguide for workload-rebalancer
Fixes part of https://github.com/karmada-io/karmada/issues/4840
[quick-preview](https://deploy-preview-628--karmada.netlify.app/zh/docs/next/userguide/scheduling/workload-rebalancer/)
=> add zh userguide for workload-rebalancer

docs/administrator/upgrading/v1.9-v1.10.md, i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.9-v1.10.md
In order to prevent users from forgetting to update the MutatingWebhookConfiguration resource during the upgrade process, relevant instructions are added.
Fixes #
=> add mutate configuration description for upgrading v1.9-v1.10

docs/administrator/upgrading/v1.9-v1.10.md, i18n/zh/docusaurus-plugin-content-docs/current/administrator/upgrading/v1.9-v1.10.md
In order to prevent users from continuing to use deprecated labels after upgrading, we have added instructions.
Fixes #
=> add deprecated label for upgrading v1.9-v1.10

docs/userguide/bestpractices/namespace-management.md
- there was no option documented about how to manually take control of namespace propagation
- the skip option did not call out that kube-.* is the default and would be replaced
fixes https://github.com/karmada-io/karmada/issues/5098
=> clean up namespace management and add manual option

docs/userguide/scheduling/resource-propagating.md
I am a user who is learning karmada for the first time.  When I was studying the `/docs/userguide/scheduling/resource-propagating` document, I repeatedly misunderstood the `api-server` pointed to by the resource used by kubectl.  I believe many people will have this question.
So I changed it a little bit here and added a Note.
=> docs: add a hint in the resource-propagation

docs/administrator/security/verify-artifacts.md, typos.toml
refer to https://github.com/karmada-io/karmada/pull/5178, we need to guide users to use slsa to verify release assets
Fixes #
=> add slsa verifier

docs/userguide/failover/application-failover.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.10/userguide/failover/application-failover.md
fix nits in application failover doc
run demo failed: `Error from server (Forbidden): error when creating "appfailover-pp.yaml": admission webhook "propagationpolicy.karmada.io" denied the request: spec.propagateDeps: Invalid value: false: application failover is set, propagateDeps must be true`, so do a simple fix.
Fixes #
=> fix nits in application failover doc

docs/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.10/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.3/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.4/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.5/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.6/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.7/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.8/administrator/migration/promote-legacy-workload.md, versioned_docs/version-v1.9/administrator/migration/promote-legacy-workload.md
/kind bug
typo error in https://karmada.io/docs/administrator/migration/promote-legacy-workload
follow the instructions to promote resource from member cluster
some errors occured:
the `-c member1` should be corrected as `-C member1`
It seems that the old versions of promote-legacy-workload still not right, so I rewrite the versioned documents.
Fixes #
=> fix: typo in promote-legacy-workload.md

docs/reference/karmada-api/common-definitions/delete-options.md, docs/reference/karmada-api/common-definitions/label-selector.md, docs/reference/karmada-api/common-definitions/node-selector-requirement.md, docs/reference/karmada-api/common-definitions/object-meta.md, docs/reference/karmada-api/common-definitions/status.md, docs/reference/karmada-api/networking-resources/multi-cluster-ingress-v1alpha1.md, docs/reference/karmada-api/networking-resources/multi-cluster-service-v1alpha1.md, docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md, docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md, docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md, docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md, docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md, docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md, docs/reference/karmada-api/work-resources/work-v1alpha1.md
add Karmada API Document for v1.11
Fixes part of https://github.com/karmada-io/karmada/issues/5466
see [preview](https://deploy-preview-679--karmada.netlify.app/docs/next/category/karmada-api)
=> add Karmada API Document for v1.11

docs/userguide/scheduling/override-policy.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/scheduling/override-policy.md
User Guide for field overrider.
Fixes #699
None
=> docs: fieldoverrider docs

docs/administrator/migration/migrate-in-batch.md, i18n/zh/docusaurus-plugin-content-docs/current/administrator/migration/migrate-in-batch.md
add administrator doc in website repo about how to do migration rollback
Part of https://github.com/karmada-io/karmada/issues/5380
=> add administrator doc in website repo about how to do migration rollback

docs/tutorials/resource-migration.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/resource-migration.md
add tutorial doc in website repo about how to do migration rollback
Fixes part of https://github.com/karmada-io/karmada/issues/5380
=> add tutorial doc in website repo about how to do migration rollback

i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/rbac-permissions-for-karmada-components.md
add docs-zh for karmada components-rbac
Part of [#5182](https://github.com/karmada-io/karmada/issues/5182)
=> add docs-zh for karmada components-rbac

docs/administrator/security/rbac-permissions-for-karmada-components.md, sidebars.js
add docs for karmada components-rbac
Part of [#5182](https://github.com/karmada-io/karmada/issues/5182)
=> add docs for karmada components-rbac

i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/components.md
Sync with the english text
Fixes #
=> [zh] Sync core-concepts/components.md

docs/reference/karmada-api/cluster-resources/cluster-v1alpha1.md, docs/reference/karmada-api/common-parameter/common-parameters.md, docs/reference/karmada-api/policy-resources/cluster-override-policy-v1alpha1.md, docs/reference/karmada-api/policy-resources/cluster-propagation-policy-v1alpha1.md, docs/reference/karmada-api/policy-resources/override-policy-v1alpha1.md, docs/reference/karmada-api/policy-resources/propagation-policy-v1alpha1.md, docs/reference/karmada-api/search-resources/resource-registry-v1alpha1.md, docs/reference/karmada-api/work-resources/resource-binding-v1alpha2.md, docs/reference/karmada-api/work-resources/work-v1alpha1.md
add Karmada API Document for v1.12
Fixes #
=> add Karmada API Document for v1.12

docs/userguide/cicd/working-with-flux.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/cicd/working-with-flux.md
/kind bug
After test, it seems helm deployment with fluxcd is not working due to the apiversion of "helmrepository" or "helmrelease".
Just removed the beta in the api version and worked !
=> remove beta apiversion

docs/tutorials/autoscaling-with-custom-metrics.md, docs/tutorials/autoscaling-with-resource-metrics.md
Fixes https://github.com/karmada-io/karmada/issues/5915
=> adds karmadactl flags for proper display

i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-custom-metrics.md, i18n/zh/docusaurus-plugin-content-docs/current/tutorials/autoscaling-with-resource-metrics.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.11/tutorials/autoscaling-with-custom-metrics.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.11/tutorials/autoscaling-with-resource-metrics.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.12/tutorials/autoscaling-with-custom-metrics.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.12/tutorials/autoscaling-with-resource-metrics.md, versioned_docs/version-v1.11/tutorials/autoscaling-with-custom-metrics.md, versioned_docs/version-v1.11/tutorials/autoscaling-with-resource-metrics.md, versioned_docs/version-v1.12/tutorials/autoscaling-with-custom-metrics.md, versioned_docs/version-v1.12/tutorials/autoscaling-with-resource-metrics.md
Refer to https://github.com/karmada-io/website/pull/763#issuecomment-2544487028
Fixes #
=> zh: adds karmadactl flags for proper display

docs/installation/install-binary.md, versioned_docs/version-v1.10/installation/install-binary.md, versioned_docs/version-v1.11/installation/install-binary.md, versioned_docs/version-v1.12/installation/install-binary.md, versioned_docs/version-v1.4/installation/install-binary.md, versioned_docs/version-v1.5/installation/install-binary.md, versioned_docs/version-v1.6/installation/install-binary.md, versioned_docs/version-v1.7/installation/install-binary.md, versioned_docs/version-v1.8/installation/install-binary.md, versioned_docs/version-v1.9/installation/install-binary.md
This PR fixes a typographical error in multiple installation documentation files where "Configurate" was incorrectly used instead of "Configure".
Fixes #772
Affected files:
- docs/installation/install-binary.md
- versioned_docs/version-v1.4/installation/install-binary.md
- versioned_docs/version-v1.5/installation/install-binary.md
- versioned_docs/version-v1.6/installation/install-binary.md
- versioned_docs/version-v1.7/installation/install-binary.md
- versioned_docs/version-v1.8/installation/install-binary.md
- versioned_docs/version-v1.9/installation/install-binary.md
- versioned_docs/version-v1.10/installation/install-binary.md
- versioned_docs/version-v1.11/installation/install-binary.md
- versioned_docs/version-v1.12/installation/install-binary.md
Thank you for reviewing this PR!
=> fixing typo in install-binary page

docs/userguide/clustermanager/cluster-registration.md, i18n/zh/docusaurus-plugin-content-docs/current/userguide/clustermanager/cluster-registration.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.12/userguide/clustermanager/cluster-registration.md, versioned_docs/version-v1.12/userguide/clustermanager/cluster-registration.md
Release v1.12 introduces a new command `unregister` to unregister pull mode member clusters. This pr updates `cluster-registration.md` to describe how to perform the process.
Fixes #
=> update cluster-registration.md to introduce how to unregister a cluster using the unregister command

blog/2025-01-17-karmada-security-audit/karmada-security-audit.md
add karmada security audit blog
Fixes #
=> add karmada security audit blog

Dockerfile, netlify.toml, package-lock.json
**Description**
This commit optimizes the Karmada website's Docker container, reducing the image size from **~796MB to ~570MB**, achieving a significant **~28% reduction**.  
The size reduction was achieved by:  
- **Using a multi-stage build approach**: One stage for building the Node modules and another for running the server runtime.  
- **Consolidating `RUN` commands**: Combining multiple `RUN` operations to reduce intermediate tarball files generated during those operations.  
/kind cleanup
N/A
**Special Notes for Reviewers**:  
- **Verification**:  
This optimization can be verified by comparing Docker image builds before and after the changes:  
- **Further Debugging**:  
For deeper insights, the optimization can be …
=> Dockerfile: reduce karmada website container image size by 28%

docs/installation/install-binary.md, i18n/zh/docusaurus-plugin-content-docs/current/installation/install-binary.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.11/installation/install-binary.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.12/installation/install-binary.md, i18n/zh/docusaurus-plugin-content-docs/version-v1.13/installation/install-binary.md, versioned_docs/version-v1.11/installation/install-binary.md, versioned_docs/version-v1.12/installation/install-binary.md, versioned_docs/version-v1.13/installation/install-binary.md
In the `install-binary.md`, [initialize-karmada](https://karmada.io/docs/installation/install-binary#initialize-karmada) is used to create the CRDs required by Karmada. However, it is placed later in the installation sequence. The correct installation sequence should be to move it before the installation of the [karmada-controller-manager](https://karmada.io/docs/installation/install-binary#install-karmada-controller-manager).
Fixes #https://github.com/karmada-io/karmada/issues/6186
=> update install-binary.md to adjust the installation order

docs/administrator/security/security-considerations.md, i18n/zh/docusaurus-plugin-content-docs/current/administrator/security/security-considerations.md
/kind cleanup
Replaced `${POD_IP}` with `$(POD_IP)` to properly reference the `POD_IP` from the environment variable.
Part of https://github.com/karmada-io/karmada/issues/6266
=> Fix syntax for referencing POD_IP

docs/administrator/compatibility/compatibility.md, i18n/zh/docusaurus-plugin-content-docs/current.json, i18n/zh/docusaurus-plugin-content-docs/current/administrator/compatibility/compatibility.md, sidebars.js
Fixes https://github.com/karmada-io/karmada/issues/2757
=> Add Kubernetes compatibility docs

i18n/zh/docusaurus-plugin-content-docs/current/developers/profiling-karmada.md
=> translate profiling-karmada.md to Chinese

docs/reference/karmadactl/karmadactl-commands/karmadactl_create.md, docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret.md
Change file name to `customization.yml` in a `karmadactl interpret` example command to be uniform with other examples. Clarify that both YAML and JSON file formats are acceptable.
Fixes #
=> clarify supported file formats in karmadactl interpret doc
